version: "3"

services:
  nginx:
    # build: ./nginx
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    working_dir: ${APP_PATH_CONTAINER}

  php:
    build: ./php-fpm
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      - "9000:9000"
    environment:
      - APP_NAME=${APP_NAME}
    working_dir: ${APP_PATH_CONTAINER}

  db:
    # platform: linux/x86_64
    # image: mysql
    image: mariadb:10.5.8
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    ports:
      - 3306:3306

  composer:
    image: composer:latest
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    working_dir: ${APP_PATH_CONTAINER}
    command: composer install

  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:8080
